#!/usr/bin/env python3
"""Generate reports/coverage.md from the data in the repository. Offline, standard library only.
Run from the repository root:  python3 scripts/coverage_report.py [--root .] [--out reports/coverage.md]
Counts what exists. It never infers, never fills gaps, and says 'no data' when a table would be empty.
Presence of an entry is not confirmation: the Leipzig-Jakarta table separates 'has an entry' from
'has an entry at evidence level A-C in review or accepted'."""
import argparse, collections, glob, json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import newrecords

def lj_aliases(meaning):
    m = meaning.lower().strip()
    base = re.sub(r"\s*\(.*?\)", "", m).strip()
    paren = re.findall(r"\((.*?)\)", m)
    out = set()
    for part in re.split(r"/", base):
        part = part.strip()
        if part: out.add(part); out.add(re.sub(r"^to ", "", part))
    if "pronoun" in base and paren:
        out = {x.strip() for x in paren[0].split("/") if x.strip()}
    out.discard("")
    return out

def norm_gloss(g):
    g = re.sub(r"\s*\(.*?\)", "", (g or "").lower()).strip().rstrip(".")
    return {g, re.sub(r"^to ", "", g)}

def kind_of(r):
    note = (r.get("form_note") or "").lower()
    if "sentence" in note: return "sentence"
    if "phrase" in note: return "phrase"
    return "word or short item"

def table(title, counter, head=("Value", "Count")):
    if not counter: return f"### {title}\n\nNo data.\n"
    rows = "\n".join(f"| {k} | {v} |" for k, v in sorted(counter.items(), key=lambda kv: (-kv[1], str(kv[0]))))
    return f"### {title}\n\n| {head[0]} | {head[1]} |\n|---|---|\n{rows}\n"

def build(root):
    entries = []
    for p in sorted(glob.glob(os.path.join(root, "datasets", "*.jsonl")) + glob.glob(os.path.join(root, "lexicon", "*", "*.jsonl"))):
        for _, r, err in newrecords.read_jsonl(p):
            if isinstance(r, dict) and r.get("id"): entries.append(r)
    texts = 0
    for p in glob.glob(os.path.join(root, "corpus", "texts", "*")):
        try: texts += len(re.findall(r"^\s*(?:-\s*)?id:\s*\"?CTG-TXT|\"id\":\s*\"CTG-TXT", open(p, encoding="utf-8").read(), re.M))
        except OSError: pass
    out = ["# Coverage report", "",
           "Generated by `scripts/coverage_report.py`. Do not edit by hand; rerun the script. It counts what is in the repository and nothing else.", ""]
    out += ["## Lexical entries", "", f"Total entries read from `datasets/` and `lexicon/*/`: **{len(entries)}**. Text records in `corpus/texts/`: **{texts}** (counted, not parsed).", ""]
    if not entries:
        out += ["No data.", ""]
    else:
        out.append(table("By state", collections.Counter(r.get("state", "missing") for r in entries), ("State", "Entries")))
        out.append(table("By evidence level", collections.Counter(r.get("evidence_level", "missing") for r in entries), ("Level", "Entries")))
        out.append(table("By kind (taken from `form_note`; a rough guide only)", collections.Counter(kind_of(r) for r in entries), ("Kind", "Entries")))
        out.append(table("By source", collections.Counter(r.get("source", "missing") for r in entries), ("Source id", "Entries")))
        out.append(table("By consent value", collections.Counter(r.get("consent", "missing") for r in entries), ("Consent", "Entries")))
        places = collections.Counter()
        for r in entries:
            pl = r.get("place")
            if isinstance(pl, dict) and pl.get("upazila"): places[f"{pl.get('district', '?')} / {pl['upazila']}"] += 1
        out.append(table("By upazila (from the `place` field; absent in current records)", places, ("District / upazila", "Entries")))
        out.append(f"Entries with a recording id or recording note: **{sum(1 for r in entries if (r.get('recording') not in (None, '', 'none')) or r.get('recording_ids'))}**. Entries marked AI-assisted: **{sum(1 for r in entries if r.get('ai_assisted'))}**.\n")
    # Leipzig-Jakarta
    out += ["## Leipzig-Jakarta 100 list", ""]
    lj = [r for _, r, _e in (t for t in newrecords.read_jsonl(os.path.join(root, "prompts", "leipzig-jakarta-100.jsonl")))] if os.path.exists(os.path.join(root, "prompts", "leipzig-jakarta-100.jsonl")) else []
    if not lj:
        out += ["No data: `prompts/leipzig-jakarta-100.jsonl` not found.", ""]
    else:
        idx = collections.defaultdict(list)
        for r in entries:
            for g in norm_gloss(r.get("english_gloss")): idx[g].append(r)
        has, firm, missing = 0, 0, []
        for p in lj:
            hits = [r for a in lj_aliases(p["meaning_en"]) for r in idx.get(a, [])]
            if hits: has += 1
            else: missing.append(p["meaning_en"])
            if any(r.get("state") in ("REVIEW", "ACCEPTED") and r.get("evidence_level") in ("A", "B", "C") for r in hits): firm += 1
        out += [f"Matching is by exact English gloss (after removing a leading 'to' and bracketed text); it does not judge whether the form is right.", "",
                f"- Meanings in the list: **{len(lj)}**",
                f"- With at least one existing entry (any state, any evidence level): **{has}**",
                f"- With an entry at evidence level A to C in review or accepted: **{firm}**", ""]
        if has == 0: out.append("No existing entry matches a meaning on the list.\n")
        out.append(f"<details><summary>Meanings with no entry ({len(missing)})</summary>\n\n" + "; ".join(missing) + "\n\n</details>\n")
    # new record types
    out += ["## Sessions, recordings and speakers", ""]
    _, _, counts, recs = newrecords.check_new_records(root)
    rows = [(k, counts.get(k, 0)) for k in ("session", "recording", "speaker")]
    out += ["| Record type | Count |", "|---|---|"] + [f"| {k}s | {n} |" for k, n in rows] + [""]
    if not any(n for _, n in rows):
        out += ["No data: no session, recording or speaker records have been added yet.", ""]
    else:
        sp = recs.get("speaker", [])
        grid = collections.Counter((f"{(s.get('place') or {}).get('district', '?')} / {(s.get('place') or {}).get('upazila', '?')}", s.get("age_band"), s.get("gender")) for s in sp)
        if grid:
            out += ["### Speaker grid (upazila, age band, gender)", "", "| Upazila | Age band | Gender | Speakers |", "|---|---|---|---|"]
            out += [f"| {k[0]} | {k[1]} | {k[2]} | {v} |" for k, v in sorted(grid.items())] + [""]
        secs = sum(r.get("duration_s", 0) for r in recs.get("recording", []))
        out += [f"Recorded time: **{secs / 60:.1f} minutes** across {counts.get('recording', 0)} file(s).", ""]
    src = recs.get("source", [])
    if src:
        c = collections.Counter(s.get("status") for s in src)
        out += ["## Source register", "", f"{len(src)} sources: " + ", ".join(f"{v} {k}" for k, v in sorted(c.items())) + ".", ""]
    return "\n".join(out).rstrip() + "\n"

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--root", default="."); ap.add_argument("--out", default=None)
    a = ap.parse_args()
    out = a.out or os.path.join(a.root, "reports", "coverage.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    text = build(a.root)
    with open(out, "w", encoding="utf-8") as f: f.write(text)
    print(f"wrote {out}")

if __name__ == "__main__": main()
